<?php
return array(
	'BE' => array(
		'installToolPassword' => 'bacb98acf97e0b6112b1d1b650b84971',
		'loginSecurityLevel' => 'rsa',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'typo3-tpl',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'localhost',
		'password' => 'main',
		'username' => 'main',
	),
	'EXT' => array(
		'extConf' => array(
			'devlog' => 'a:12:{s:10:"maxLogRuns";s:2:"15";s:14:"entriesPerPage";s:2:"25";s:7:"maxRows";s:4:"1000";s:8:"optimize";s:1:"0";s:8:"dumpSize";s:7:"1000000";s:11:"minLogLevel";s:2:"-1";s:11:"excludeKeys";s:0:"";s:14:"highlightStyle";s:60:"padding: 2px; background-color: #fc3; border: 1px solid #666";s:16:"refreshFrequency";s:1:"2";s:13:"prototypePath";s:0:"";s:11:"autoCleanup";s:1:"0";s:8:"__meta__";N;}',
			'fed' => 'a:9:{s:29:"enableBackendRecordController";s:1:"0";s:24:"enableFluidPageTemplates";s:1:"0";s:42:"enableFluidPageTemplateVariableInheritance";s:1:"0";s:31:"enableFallbackFluidPageTemplate";s:1:"0";s:18:"enableSolrFeatures";s:1:"0";s:21:"enableFrontendPlugins";s:1:"0";s:30:"enableIntegratedBackendLayouts";s:1:"0";s:28:"increaseExtbaseCacheLifetime";s:1:"0";s:35:"disableAutomaticTypoScriptInclusion";s:1:"0";}',
			'fluidcontent' => 'a:0:{}',
			'fluidcontent_bootstrap' => 'a:0:{}',
			'fluidpages' => 'a:0:{}',
			'flux' => 'a:2:{s:9:"debugMode";s:1:"0";s:7:"compact";s:1:"0";}',
			'gridelements' => 'a:0:{}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'recycler' => 'a:0:{}',
			'saltedpasswords' => 'a:2:{s:3:"FE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}s:3:"BE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}}',
			'seo_basics' => 'a:2:{s:10:"xmlSitemap";s:1:"1";s:16:"sourceFormatting";s:1:"1";}',
			'template' => 'a:0:{}',
			'vhs' => 'a:0:{}',
			'ws_less' => 'a:0:{}',
		),
		'extListArray' => array(
			'info',
			'perm',
			'func',
			'filelist',
			'about',
			'version',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'rtehtmlarea',
			'css_styled_content',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'form',
			'rsaauth',
			'saltedpasswords',
			'adodb',
			'dbal',
			'recycler',
			'gridelements',
			'realurl',
			'flux',
			'vhs',
			'fluidpages',
			'fluidcontent',
			'fluidcontent_bootstrap',
			'template',
			'ws_less',
			'devlog',
		),
	),
	'FE' => array(
		'loginSecurityLevel' => 'rsa',
	),
	'SYS' => array(
		'compat_version' => '6.1',
		'curlUse' => '1',
		'encryptionKey' => '84b5246fb2c443002224b20510ea5cd1ecdff6464b513cd95c56829c6df8904ff06d78eca41d81dd6fa971501f358b52',
		'sitename' => 'New TYPO3 site',
	),
);
?>